apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft3
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0-alpine
        ports:
         - name: default
           containerPort: 25565
         - name: rcon
           containerPort: 25575
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: EULA
          value: "TRUE"
        - name: MOTD
          value: "HELLOWWORLD"
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: default
    protocol: TCP
    port: 25565
    targetPort: 25565
  - name: rcon
    protocol: TCP
    port: 25575
    targetPort: 25575
  selector:
    app: minecraft